import "server-only";

import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { GeoJsonMap } from "@chronica/shared";

let punicWarsMap: GeoJsonMap | undefined;

/**
 * The 270 BCE map: 6,321 provinces and the towns in them, generated by
 * `scripts/map-gen` and described in `docs/plans/imperator-density-map.md`. It is
 * ten megabytes of text, so it is read the first time somebody asks for it and
 * kept for the life of the process.
 */
export function punicWarsGeoJson(): GeoJsonMap {
  punicWarsMap ??= JSON.parse(readFileSync(join(process.cwd(), "public", "maps", "punic-wars-provinces.geojson"), "utf8")) as GeoJsonMap;
  return punicWarsMap;
}
