import type { DynamicMapOverlay, GeoJsonPosition } from "@chronica/shared";
import { polityColorFromId } from "./geo-projection";
import { provinceContains, type SharedBoundary, type StaticProvince, type StaticWorldGeometry, type WorldBounds } from "./world-geometry";

export type BorderClassification = "internal_province" | "country_border" | "coast";
export interface PoliticalBorderSegment extends SharedBoundary { readonly classification: BorderClassification; }
export interface TerritorialComponent { readonly provinceIds: readonly string[]; readonly totalArea: number; readonly weightedCentroid: GeoJsonPosition; readonly bounds: WorldBounds; }
export interface PoliticalLabelGeometry { readonly anchor: GeoJsonPosition; readonly angle: number; readonly availableLength: number; readonly territoryArea: number; readonly priority: number; readonly recommendedFontSize: number; readonly recommendedTracking: number; }
export interface PoliticalTerritory { readonly polityId: string; readonly name: string; readonly colour: string; readonly components: readonly TerritorialComponent[]; readonly primaryComponent: TerritorialComponent; readonly label: PoliticalLabelGeometry; }
export interface PoliticalMapState { readonly ownerByProvince: ReadonlyMap<string, string | null>; readonly territories: readonly PoliticalTerritory[]; readonly borderSegments: readonly PoliticalBorderSegment[]; }
export interface PoliticalOverlayInput { readonly polities: DynamicMapOverlay["polities"]; readonly provinces: DynamicMapOverlay["provinces"]; }

function boundsFor(provinces: readonly StaticProvince[]): WorldBounds { return provinces.reduce<WorldBounds>((bounds, province) => ({ minX: Math.min(bounds.minX, province.bounds.minX), minY: Math.min(bounds.minY, province.bounds.minY), maxX: Math.max(bounds.maxX, province.bounds.maxX), maxY: Math.max(bounds.maxY, province.bounds.maxY) }), { minX: Infinity, minY: Infinity, maxX: -Infinity, maxY: -Infinity }); }
function componentFor(startId: string, available: Set<string>, world: StaticWorldGeometry): TerritorialComponent { const queue = [startId]; available.delete(startId); const provinceIds: string[] = []; while (queue.length) { const id = queue.pop()!; provinceIds.push(id); for (const neighbor of world.provinceById.get(id)?.neighborIds ?? []) if (available.delete(neighbor)) queue.push(neighbor); } const provinces = provinceIds.map((id) => world.provinceById.get(id)!).filter(Boolean); const totalArea = provinces.reduce((sum, province) => sum + province.area, 0); return { provinceIds: provinceIds.sort(), totalArea, weightedCentroid: [provinces.reduce((sum, province) => sum + province.centroid[0] * province.area, 0) / totalArea, provinces.reduce((sum, province) => sum + province.centroid[1] * province.area, 0) / totalArea], bounds: boundsFor(provinces) }; }
function weightedQuantile(samples: readonly { value: number; weight: number }[], quantile: number) { const sorted = [...samples].sort((a, b) => a.value - b.value); const threshold = sorted.reduce((sum, sample) => sum + sample.weight, 0) * quantile; let cumulative = 0; for (const sample of sorted) { cumulative += sample.weight; if (cumulative >= threshold) return sample.value; } return sorted.at(-1)?.value ?? 0; }
function labelGeometry(component: TerritorialComponent, world: StaticWorldGeometry, name: string): PoliticalLabelGeometry {
  const provinces = component.provinceIds.map((id) => world.provinceById.get(id)!).filter(Boolean); const center = component.weightedCentroid; let cxx = 0; let cxy = 0; let cyy = 0;
  for (const province of provinces) { const x = province.centroid[0] - center[0]; const y = province.centroid[1] - center[1]; cxx += province.area * x * x; cxy += province.area * x * y; cyy += province.area * y * y; }
  cxx /= component.totalArea; cxy /= component.totalArea; cyy /= component.totalArea; const discriminant = Math.sqrt((cxx - cyy) ** 2 + 4 * cxy ** 2); const largest = (cxx + cyy + discriminant) / 2; const smallest = (cxx + cyy - discriminant) / 2; const anisotropy = smallest <= Number.EPSILON ? Infinity : largest / smallest;
  let angle = anisotropy >= 1.3 ? Math.atan2(2 * cxy, cxx - cyy) / 2 * 180 / Math.PI : 0; if (angle > 90) angle -= 180; if (angle <= -90) angle += 180;
  const radians = angle * Math.PI / 180; const axisX = Math.cos(radians); const axisY = Math.sin(radians); const projections = provinces.map((province) => ({ value: (province.centroid[0] - center[0]) * axisX + (province.centroid[1] - center[1]) * axisY, weight: province.area })); const availableLength = Math.max(.8, weightedQuantile(projections, .95) - weightedQuantile(projections, .05));
  const anchor = provinces.some((province) => provinceContains(province, center)) ? center : [...provinces].sort((a, b) => ((a.centroid[0] - center[0]) ** 2 + (a.centroid[1] - center[1]) ** 2) - ((b.centroid[0] - center[0]) ** 2 + (b.centroid[1] - center[1]) ** 2))[0]!.centroid; const glyphUnits = Math.max(2, name.length * .64 + Math.max(0, name.length - 1) * .12);
  return { anchor, angle, availableLength, territoryArea: component.totalArea, priority: component.totalArea, recommendedFontSize: Math.max(1.15, Math.min(5.2, availableLength * .88 / glyphUnits)), recommendedTracking: Math.max(.1, Math.min(.45, availableLength / Math.max(3, name.length) * .12)) };
}

/** Derives ownership, territorial components, borders, and labels without renderer state. */
export function derivePoliticalMapState(world: StaticWorldGeometry, overlay: PoliticalOverlayInput | null): PoliticalMapState {
  const ownerByProvince = new Map<string, string | null>(world.provinces.map((province) => [province.id, null]));
  if (!overlay) return { ownerByProvince, territories: [], borderSegments: world.sharedBoundaries.map((boundary) => ({ ...boundary, classification: boundary.provinceB === null ? "coast" as const : "internal_province" as const })) };
  for (const province of overlay.provinces) if (world.provinceById.has(province.provinceId)) ownerByProvince.set(province.provinceId, province.controllerPolityId);
  const names = new Map(overlay.polities.map((polity) => [polity.polityId, polity.name])); const ownedByPolity = new Map<string, Set<string>>();
  for (const [provinceId, owner] of ownerByProvince) if (owner !== null) { const owned = ownedByPolity.get(owner) ?? new Set<string>(); owned.add(provinceId); ownedByPolity.set(owner, owned); }
  const territories: PoliticalTerritory[] = [];
  for (const [polityId, owned] of ownedByPolity) { const name = names.get(polityId); if (!name) continue; const remaining = new Set(owned); const components: TerritorialComponent[] = []; while (remaining.size) components.push(componentFor(remaining.values().next().value as string, remaining, world)); components.sort((a, b) => b.totalArea - a.totalArea || a.provinceIds[0]!.localeCompare(b.provinceIds[0]!)); const primaryComponent = components[0]!; territories.push({ polityId, name, colour: polityColorFromId(polityId), components, primaryComponent, label: labelGeometry(primaryComponent, world, name) }); }
  const borderSegments = world.sharedBoundaries.map((boundary) => { if (boundary.provinceB === null) return { ...boundary, classification: "coast" as const }; const a = ownerByProvince.get(boundary.provinceA) ?? null; const b = ownerByProvince.get(boundary.provinceB) ?? null; return { ...boundary, classification: a !== b ? "country_border" as const : "internal_province" as const }; });
  return { ownerByProvince, territories: territories.sort((a, b) => b.label.priority - a.label.priority), borderSegments };
}
